Braian.quinteros/test
BQuinteros/CalculadoraMVP pull request #10
Opened 2019-11-12 15:11 UTC by BQuinteros

Added test to method onNumberPressed and coverage its ok.
![Test](https://user-images.githubusercontent.com/56684696/68683408-7dd1b880-0545-11ea-9f22-c34b4f04d499.png)

2019-11-12 15:30 UTC, BQuinteros commented
Added CleanAllTest and modified onNumberPressedTest. Coverage is okey.
![ClearAllTest](https://user-images.githubusercontent.com/56684696/68684964-208b3680-0548-11ea-82b8-a486f9f58475.png)
![onNumberPressedTest](https://user-images.githubusercontent.com/56684696/68684965-208b3680-0548-11ea-9ad4-2081797f674e.png)

2019-11-13 16:24 UTC, regmarcos commented
Hi! Now the CalculatorPresenter class has 100% coverage.

![Anotación 2019-11-13 132150](https://user-images.githubusercontent.com/56684939/68782893-dde55f00-0618-11ea-8ed1-e1c4dc279979.png)

2019-11-13 17:19 UTC, lucianoeli commented on app/src/test/java/com/example/calculadoramvp/mvp/model/presenter/PresenterTest.java
> +}
Delete this class if its gonna be empty

2019-11-13 17:20 UTC, SartiMau requested changes

2019-11-13 17:20 UTC, SartiMau commented on app/src/test/java/com/example/calculadoramvp/ExampleUnitTest.java
>  import static org.junit.Assert.*;
not use wildcard imports pls

2019-11-13 17:20 UTC, SartiMau commented on app/src/test/java/com/example/calculadoramvp/mvp/model/presenter/PresenterTest.java
> +public class PresenterTest {
if this is not needed pls remove it

2019-11-13 17:32 UTC, SartiMau approved these changes

2019-11-13 17:33 UTC, merged